name: Test builds

on:
  push:
    branches-ignore: djgpp-ppa
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        env:
          -
            TARGET: i386-pc-msdosdjgpp
            PACKAGES: binutils gcc djgpp-2.05 watt32
          -
            TARGET: i386-pc-msdosdjgpp
            PACKAGES: binutils gcc djgpp-cvs watt32
          -
            TARGET: i386-pc-msdosdjgpp
            PACKAGES: gdb
          -
            TARGET: arm-eabi
            PACKAGES: binutils gcc newlib
          -
            TARGET: arm-eabi
            PACKAGES: gdb
          -
            TARGET: avr
            PACKAGES: binutils gcc avr-libc
          -
            TARGET: avr
            PACKAGES: gdb avarice simulavr avrdude
          -
            TARGET: ia16-elf
            PACKAGES: binutils gcc newlib

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies (ubuntu)
        if: contains(matrix.os, 'ubuntu')
        continue-on-error: true
        run: ./script/ci/deps-ubuntu.sh

      - name: Install dependencies (macos)
        if: contains(matrix.os, 'macos')
        continue-on-error: true
        run: ./script/ci/deps-macos.sh

      - name: Cache sources
        uses: actions/cache@v5
        with:
          path: download
          key: testbuild-sources-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-sources-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: testbuild-ccache-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-ccache-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Download sources
        env:
          TARGET: ${{ matrix.env.TARGET }}
          PACKAGES: ${{ matrix.env.PACKAGES }}
        run: ./script/ci/build.sh --only-download

      - name: Build
        env:
          TARGET: ${{ matrix.env.TARGET }}
          PACKAGES: ${{ matrix.env.PACKAGES }}
        run: ./script/ci/build.sh --no-download

      - name: Save installed files
        uses: actions/upload-artifact@v7
        with:
          name: install_${{ matrix.os }}_${{ matrix.env.TARGET }}_${{ matrix.env.PACKAGES }}
          path: install/tmp/cross/
          include-hidden-files: true

      - name: Save build files
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: build_${{ matrix.os }}_${{ matrix.env.TARGET }}_${{ matrix.env.PACKAGES }}
          path: build/
          include-hidden-files: true
          retention-days: 3

      - name: Clear and pack git sources before caching
        run: /bin/bash ./script/ci/clean.sh
