name: Static-linked toolchain build

on:
  push:
    branches: build-static

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          -
            TARGET: i386-pc-msdosdjgpp
            PACKAGES: binutils gcc djgpp-cvs watt32

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies (ubuntu)
        if: contains(matrix.os, 'ubuntu')
        continue-on-error: true
        run: ./script/ci/deps-ubuntu.sh

      - name: Install dependencies (macos)
        if: contains(matrix.os, 'macos')
        continue-on-error: true
        run: ./script/ci/deps-macos.sh

      - name: Cache sources
        uses: actions/cache@v5
        with:
          path: download
          key: testbuild-sources-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-sources-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: testbuild-ccache-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-${{ github.sha }}
          restore-keys: |
            testbuild-ccache-${{ matrix.os }}-${{ matrix.env.TARGET }}-${{ matrix.env.PACKAGES }}-

      - name: Download sources
        env:
          TARGET: ${{ matrix.env.TARGET }}
          PACKAGES: ${{ matrix.env.PACKAGES }}
        run: ./script/select-script.sh --only-download

      - name: Build
        env:
          TARGET: ${{ matrix.env.TARGET }}
          PACKAGES: ${{ matrix.env.PACKAGES }}
          LDFLAGS: -static
        run: ./script/select-script.sh --no-download

      - name: Save installed files
        uses: actions/upload-artifact@v7
        with:
          name: install-static_${{ matrix.os }}_${{ matrix.env.TARGET }}_${{ matrix.env.PACKAGES }}
          path: install/tmp/cross/
          include-hidden-files: true

      - name: Clear and pack git sources before caching
        run: |
          find download/*/* ! -wholename '*/.git/*' -delete || true
          cd download
          for DIR in */; do
            DIR=${DIR%/}
            tar -c -f $DIR-git.tar $DIR
          done
          rm -rf */
